### PR TITLE
Set correct units for memory usage

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@jamesob untested, since I don't have codespeed installed. Also, I believe it is required to delete the existing benches completely. Just wiping the db might not be sufficient.

**Comment by jamesob** [comment]
No delete necessary; just ran a migration. For future reference:

selection_007

**Comment by MarcoFalke** [comment]
Ah thx

I guess my patch makes still sense in the long run. In case we add new
benchmarks

**Comment by jamesob** [comment]
Found this during localhost testing:
```
2018-06-22 15:54:04,316 __main__ [INFO] Running benchmark 'microbench'
Traceback (most recent call last):
  File "./runner/run_bench.py", line 606, in <module>
    run_benches()
  File "./runner/run_bench.py", line 339, in run_benches
    median, max_, min_, executable='bench-bitcoin')
TypeError: send_to_codespeed() takes 2 positional arguments but 4 positional arguments (and 1 keyword-only argument) were given
```

**Comment by jamesob** [comment]
@MarcoFalke yup, agree the patch is good. I'm testing for merge.

**Comment by MarcoFalke** [comment]
Sry, need to add min=min_, max=max_ or so to that line (named args)

**Comment by jamesob** [comment]
Tested locally & fixed push. Nice change.

**Pull request merged**
