### PR TITLE
Report to slack if microbench fails

### PR DESCRIPTION
**Pull request by jamesob**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Would the logger also end up on slack?

Asking because of https://github.com/chaincodelabs/bitcoin-perfmonitor/pull/21/files#diff-5e1019f9de2a2206be6251061a27210bR471

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by jamesob** [comment]
> Would the logger also end up on slack?

The microbench doesn't actually use `_try_execute_and_report` so nothing would trigger a log with level at or above WARNING.

**Comment by MarcoFalke** [comment]
My question was kinda unrelated, just asking to see what would happen if the functional tests failed.

**Pull request merged**
